# Generated by Django 4.0.6 on 2024-06-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0007_genero_foto_pelicula_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='estado',
        ),
        migrations.AddField(
            model_name='director',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotoDirector'),
        ),
    ]
