databases:
  - name: servidorDiego
    plan: free
    databaseName: dbcine
    user: diego

services:
  - type: web
    plan: free
    name: cineUTC
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cineUTC.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorDiego
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cineutc-x1j8.onrender.com

# set DATABASE_URL=postgresql://diego:DCQdyWHiYFwqOhrzt6r8qzQL9Kp0hXpL@dpg-cqlpki3v2p9s73bfvqjg-a.oregon-postgres.render.com/dbcine_x2vs